
version: "2.4"

services:
  
  part05:
    image: server:part05
    build: 
      context: ./06/05
      dockerfile: Dockerfile
    container_name: server05

  part06:
    image: nginx
    build:
      context: ./06/06
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    container_name: server06
      
